### ISSUE TITLE
Insight on cyclic encoding

### ISSUE THREAD

**Issue by CarlosGomes98** [langnico/global-canopy-height-model#5]
Hi! Thanks for open sourcing the code! I was wondering if you could provide some insight into the cyclic encoding.

I see that from the latitude and longitude you seem to keep the latitude as raw values (-90 to 90 I assume) and only the longitude receives the positional encoding, which seems to be divided by 360. I there a reason why this treatment is applied only to the longitude?

Thanks in advance for any insights youre able to share!

**Comment by langnico** [comment]
Hi, 
the motivation behind the cyclic encoding is to ensure that there is no "jump" from 180° West to 180° East. This is not directly needed for latitude (N/S), but could be applied as well. We convert degrees into radians. Note that all input bands are standard normalized before passed to the model (subtract the mean divide by the standard deviation).

Best regards
